#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

picom --experimental-backends &

#urxvt -name x &

#urxvt -name pro -e htop &


$HOME/.config/polybar/launch.sh 
$HOME/.config/bspwm/external_monitors.sh



bspc config border_width         2.5
bspc config window_gap          10
bspc config active_border_color '#8ec07c'
bspc config focused_border_color '#a89984'
bspc config normal_border_color '#000000'

bspc config top_padding		  0

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a firefox desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

#bspc rule -a URxvt:pro desktop='^1' state=floating rectangle=780x590+10+40


#bspc rule -a URxvt:x desktop='^1' state=floating rectangle=770x1018+1135+40
